### ISSUE TITLE
Permission required :) inside cors 

### ISSUE THREAD

**Issue by priyansh18** [jugshaurya/productive-weekday#24]
Hi, Shaurya. I would like to request cors access to my personal website.

Please add priyanshsinghal.com in your whitelist.

Thanks in Advance.

**Comment by priyansh18** [comment]
Kindly allow me ASAP

**Comment by jugshaurya** [comment]
ok adding https://www.priyanshsinghal.com/ into my whitelist.

**Comment by jugshaurya** [comment]
Can u please check, I have added it. Will commit once confirmed.

**Comment by priyansh18** [comment]
Thank you @jugshaurya for helping and considering my request.
